# Generated by Django 4.1.7 on 2023-04-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_url',
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.users'),
            preserve_default=False,
        ),
    ]
